### ISSUE TITLE
Version using 16 bit Open Watcom on Linux

### ISSUE THREAD

**Issue by toncho11** [FrenkelS/doomtd3#10]
Is it possible to add a version that compiles doomtd3 using Open Watcom on Linux? 

So you are using `wmake` on Windows to compile the source? `wmake` handles the https://github.com/FrenkelS/doomtd3/blob/main/makefile.w16 What is `wmake`?

**Comment by FrenkelS** [comment]
I'll give it a shot.

`wmake` is the `make` utility that comes with Watcom.

**Comment by FrenkelS** [comment]
I've added `setenvwc.sh` and `compwc16.sh`, and made some changes to `makefile.w16` and `wc16doom.lnk`.
And now it runs on my Ubuntu machine.

**Comment by toncho11** [comment]
Nice! Thanks! Then these need to be modified for the ELKS version because they still generate a DOS executable, right?

**Comment by FrenkelS** [comment]
yes
