### ISSUE TITLE
Amiga build works in FS-UAE emulating an Amiga 500 with a 68020 CPU, but not the default 68000 CPU

### ISSUE THREAD

**Issue by FrenkelS** [FrenkelS/doomtd3#4]
Amiga build works in FS-UAE emulating an Amiga 500 with a 68020 CPU, but not the default 68000 CPU.

```
Software Failure. Press left mouse button to continue.
Guru Meditation #00000003.00C05E30
```

**Comment by FrenkelS** [comment]
It works in WinUAE when I set the compatibility option one tick lower.

**Comment by Swizpig** [comment]
00000003 is an address error, trying to move more than a byte from an odd (as in, not even) address. 68020+ apparently changes this so it's a performance hit but not an exception/error. Something's probably misaligned somewhere.

I've managed to get this compiling but not actually working yet with VBCC, I'll poke around a bit.

**Comment by FrenkelS** [comment]
Interesting.
I guess it has something to do with a packed struct like [line_t](https://github.com/FrenkelS/doomtd3/blob/main/r_defs.h#L176), which is 47 bytes in size.

**Comment by FrenkelS** [comment]
yup, that was the problem
